name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: target/release/terbium
  
  build-debug-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: debug
        path: target/debug/terbium

  clippy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run clippy
      run: cargo clippy --all-features -- -D clippy::all -D clippy::pedantic -D clippy::nursery -D clippy::cargo
    
    
